In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("houseprice.csv")

In [12]:
data.dropna(inplace=True)

In [13]:
data

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0.0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
5,Owner,0.0,0,3,BHK,1250.000000,1,1,"South Chittoor,Kochi",10.033280,76.282571,42.0
7,Owner,0.0,1,3,BHK,1181.012946,1,1,"Kharar,Mohali",30.740000,76.650000,52.0
10,Owner,0.0,0,3,BHK,1350.308642,1,1,"Deshbandhu Para,Siliguri",26.724219,88.326357,35.0
11,Dealer,0.0,0,2,BHK,1333.010179,1,1,"Hebbal,Bangalore",13.040340,77.591347,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,Owner,0.0,0,3,BHK,2500.000000,1,1,"Shamshabad Road,Agra",27.140626,78.043277,45.0
29447,Owner,0.0,0,2,BHK,769.230769,1,1,"E3-108, Lake View Recidency,,Vapi",39.945409,-86.150721,16.0
29448,Dealer,0.0,0,2,BHK,1022.641509,1,1,"Ajmer Road,Jaipur",26.928785,75.828002,27.1
29449,Owner,0.0,0,2,BHK,927.079009,1,1,"Sholinganallur,Chennai",12.900150,80.227910,67.0
29450,Dealer,0.0,1,2,BHK,896.774194,1,1,"Jagatpura,Jaipur",26.832353,75.841749,27.8

### 1) Find the dealer who has under construction & RERA approved with 2BHK flat but area of that flat should be between 900 to 1300 sq.feet

In [14]:
a1=data.loc[(data["POSTED_BY"]=="Dealer")&(data["UNDER_CONSTRUCTION"]==1) & (data["RERA"]==1) & (data["BHK_NO."]==2) &
            (data["SQUARE_FT"]>=900) & (data["SQUARE_FT"]<=1300)]

In [15]:
a1

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
36,Dealer,1.0,1,2,BHK,1020.087884,0,1,"Wakad,Pune",18.599300,73.762500,65.0
49,Dealer,1.0,1,2,BHK,1228.571429,0,1,"Bolar,Mangalore",12.843852,74.845271,51.6
62,Dealer,1.0,1,2,BHK,906.266183,0,0,"Balkum,Lalitpur",24.690280,78.418890,70.0
233,Dealer,1.0,1,2,BHK,995.831403,0,0,"Sevasi,Vadodara",22.311323,73.121275,21.5
237,Dealer,1.0,1,2,BHK,1100.000000,0,1,"Majiwada,Mumbai",19.218498,72.992114,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29182,Dealer,1.0,1,2,BHK,1045.016077,0,1,"Sector-66A Mohali,Mohali",30.661104,76.746082,45.5
29188,Dealer,1.0,1,2,BHK,1258.524489,0,1,"Varthur,Bangalore",12.940700,77.746600,60.9
29209,Dealer,1.0,1,2,BHK,1099.928109,0,1,"Kharadi,Pune",18.543800,73.943800,76.5
29366,Dealer,1.0,1,2,BHK,992.025640,0,1,"Powai,Lalitpur",19.120000,72.910000,260.0
29439,Dealer,1.0,1,2,BHK,975.609756,0,1,"Laxmi Nagar,Lalitpur",22.281215,70.789479,120.0

### 2) Find those flats those are ready to move but not approved by RERA and cost of that flat that should be between 50 to 75 lakhs.

In [16]:
b1=data.loc[(data["READY_TO_MOVE"]==1) & (data["RERA"]==0) & (data["TARGET(PRICE_IN_LACS)"]>=50) & 
            (data["TARGET(PRICE_IN_LACS)"]<=75)]

In [17]:
b1

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0.0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
24,Dealer,0.0,0,2,BHK,1219.809710,1,1,"Narendra Nagar,Nagpur",21.105779,79.078497,50.0
30,Dealer,0.0,0,3,BHK,1400.107701,1,1,"Sector 84 Faridabad,Faridabad",28.404730,77.367514,52.0
32,Owner,0.0,0,2,BHK,1150.146382,1,1,"Indra Colony,Jaipur",26.586306,74.873234,55.0
35,Owner,0.0,0,3,BHK,1174.210077,1,1,"Thalambur,Chennai",12.852171,80.216826,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29420,Owner,0.0,0,3,BHK,1274.755293,1,1,"Narendrapur,Kolkata",22.439170,88.395830,56.0
29426,Dealer,0.0,0,3,BHK,1816.666667,1,1,"Sirsi Road,Jaipur",27.073397,75.594316,54.5
29433,Owner,0.0,0,2,BHK,1195.028681,1,1,"Hulimavu,Bangalore",12.876691,77.599080,50.0
29434,Owner,0.0,0,3,BHK,1700.404858,1,1,"Sanganer,Jaipur",26.773189,75.611910,63.0
29449,Owner,0.0,0,2,BHK,927.079009,1,1,"Sholinganallur,Chennai",12.900150,80.227910,67.0

### 3) Find those owners and dealers who has 2BHK & 3BHK flats and area of that flat is less than 1000 sq.feet also cost is greater than 45 lakh.

In [18]:
c1=data.loc[((data["POSTED_BY"]=="Owner") | (data["POSTED_BY"]=="Dealer")) & ((data["BHK_NO."]==2) | (data["BHK_NO."]==3)) & 
            (data["SQUARE_FT"]<=1000) & (data["TARGET(PRICE_IN_LACS)"]>=45)]

In [19]:
c1

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
20,Owner,0.0,0,2,BHK,881.143529,1,1,"Poonamallee,Chennai",13.050000,80.110000,45.0
34,Dealer,0.0,1,2,BHK,857.786197,1,0,"Mulund (West),Maharashtra",19.175900,72.952200,240.0
50,Owner,0.0,0,2,BHK,986.016493,1,1,"Ayanambakkam,Chennai",13.077175,80.151453,55.0
56,Owner,0.0,0,2,BHK,950.014616,1,1,"Nandanwan Phases 2,Aurangabad",19.888790,75.343440,65.0
62,Dealer,1.0,1,2,BHK,906.266183,0,0,"Balkum,Lalitpur",24.690280,78.418890,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29387,Dealer,0.0,1,2,BHK,999.070632,1,1,"Mira Road East,Lalitpur",19.283600,72.867500,86.0
29400,Dealer,1.0,1,2,BHK,511.555677,0,0,"Anjurdive,Maharashtra",18.960000,72.820000,56.0
29401,Dealer,0.0,0,2,BHK,556.818709,1,1,"Dahisar (East),Mumbai",19.256471,72.868815,120.0
29439,Dealer,1.0,1,2,BHK,975.609756,0,1,"Laxmi Nagar,Lalitpur",22.281215,70.789479,120.0
29449,Owner,0.0,0,2,BHK,927.079009,1,1,"Sholinganallur,Chennai",12.900150,80.227910,67.0

### 4) Find those Owners and Dealers who has RERA approved with 2BHK and 3BHK flats then incerement their target price by 5 lakhs.

In [22]:
d1=data.loc[((data["POSTED_BY"]=="Owner") | (data["POSTED_BY"]=="Dealer")) & (data["RERA"]==1) & ((data["BHK_NO."]==2) | (data["BHK_NO."]==3))]

In [23]:
d1

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
7,Owner,0.0,1,3,BHK,1181.012946,1,1,"Kharar,Mohali",30.740000,76.650000,52.0
13,Owner,0.0,1,2,BHK,1122.171946,1,1,"Sector-119 Noida,Noida",28.587711,77.403123,62.0
15,Dealer,1.0,1,3,BHK,1394.117647,0,1,"Sector-150 Noida,Noida",28.429614,77.481711,71.1
17,Dealer,1.0,1,3,BHK,2124.896706,0,1,"Konanakunte,Bangalore",12.885500,77.563800,180.0
19,Dealer,0.0,1,3,BHK,2178.649237,1,1,"Kogilu,Bangalore",13.092356,77.613468,120.0
...,...,...,...,...,...,...,...,...,...,...,...,...
29430,Owner,0.0,1,3,BHK,1265.060241,1,1,"Chromepet,Chennai",12.951610,80.140970,63.0
29436,Owner,1.0,1,2,BHK,1175.132676,0,1,"Whitefield,Bangalore",12.995893,77.761394,62.0
29439,Dealer,1.0,1,2,BHK,975.609756,0,1,"Laxmi Nagar,Lalitpur",22.281215,70.789479,120.0
29443,Dealer,0.0,1,3,BHK,1161.194975,1,1,"Marol,Maharashtra",19.111438,72.878724,220.0
29450,Dealer,0.0,1,2,BHK,896.774194,1,1,"Jagatpura,Jaipur",26.832353,75.841749,27.8

In [26]:
With_Increment=[]
for x in d1["TARGET(PRICE_IN_LACS)"]:
    x=x+5
    With_Increment.append(x)
With_Increment

[57.0,
 67.0,
 76.1,
 185.0,
 125.0,
 60.0,
 38.0,
 245.0,
 70.0,
 70.0,
 255.0,
 56.6,
 76.9,
 75.0,
 27.1,
 285.0,
 215.0,
 65.0,
 86.5,
 29.9,
 47.0,
 145.0,
 65.4,
 55.0,
 53.0,
 69.9,
 43.0,
 51.0,
 87.0,
 16.0,
 335.0,
 105.0,
 62.9,
 185.0,
 38.9,
 104.0,
 115.0,
 115.0,
 95.0,
 84.5,
 145.0,
 155.0,
 115.0,
 165.0,
 145.0,
 84.0,
 75.0,
 26.5,
 115.0,
 105.0,
 50.9,
 225.0,
 53.0,
 51.0,
 125.0,
 55.2,
 49.9,
 115.0,
 35.0,
 165.0,
 55.0,
 67.9,
 42.5,
 70.5,
 104.0,
 28.0,
 175.0,
 115.0,
 96.0,
 395.0,
 375.0,
 105.0,
 115.0,
 99.0,
 45.6,
 90.0,
 41.1,
 51.6,
 50.0,
 48.0,
 355.0,
 195.0,
 56.0,
 83.5,
 81.5,
 72.0,
 71.4,
 155.0,
 31.3,
 105.0,
 175.0,
 175.0,
 235.0,
 102.0,
 68.0,
 55.0,
 115.0,
 255.0,
 75.0,
 305.0,
 115.0,
 83.0,
 125.0,
 165.0,
 40.0,
 135.0,
 35.0,
 185.0,
 83.0,
 54.0,
 92.0,
 99.0,
 60.5,
 245.0,
 7285.0,
 56.0,
 102.6,
 83.0,
 54.6,
 51.0,
 165.0,
 34.5,
 77.0,
 375.0,
 53.4,
 115.0,
 28.5,
 135.0,
 205.0,
 68.8,
 135.0,
 355.0,
 46.0,
 105.0,
 185.0,
 88.0,
 65.0,
 62.9,
 305.0,
 38.7,
 75.0,
 73.4,
 64.5,
 125.0,
 105.0,
 185.0,
 46.0,
 125.0,
 275.0,
 49.0,
 53.1,
 59.9,
 115.0,
 70.0,
 56.0,
 92.5,
 60.0,
 27.5,
 185.0,
 195.0,
 185.0,
 475.0,
 36.7,
 35.6,
 90.0,
 104.0,
 69.5,
 37.0,
 98.0,
 145.0,
 395.0,
 45.0,
 135.0,
 57.0,
 70.0,
 37.0,
 125.0,
 79.5,
 100.0,
 52.0,
 58.0,
 68.9,
 125.0,
 77.0,
 125.0,
 53.0,
 86.3,
 70.0,
 26.9,
 145.0,
 105.0,
 115.0,
 65.0,
 42.0,
 125.0,
 26.8,
 74.3,
 92.0,
 54.8,
 52.3,
 28.9,
 135.0,
 46.5,
 70.2,
 100.0,
 48.0,
 31.5,
 54.0,
 104.0,
 115.0,
 115.0,
 90.0,
 135.0,
 115.0,
 52.2,
 375.0,
 105.0,
 50.0,
 95.0,
 60.0,
 86.0,
 77.0,
 29.9,
 100.9,
 45.0,
 95.0,
 96.0,
 63.0,
 115.0,
 165.0,
 85.0,
 54.0,
 59.0,
 92.0,
 255.0,
 435.0,
 39.0,
 25.6,
 29.5,
 9155.0,
 53.5,
 62.4,
 65.0,
 61.0,
 75.0,
 68.0,
 80.0,
 39.5,
 81.0,
 67.0,
 105.0,
 100.0,
 105.0,
 59.5,
 245.0,
 34.0,
 155.0,
 52.3,
 71.0,
 155.0,
 50.0,
 38.0,
 275.0,
 205.0,
 45.0,
 46.8,
 75.0,
 54.0,
 52.7,
 115.0,
 145.0,
 40.9,
 70.0,
 135.0,
 39.0,
 45.0,
 175.0,
 235.0,
 86.0,
 48.0,
 185.0,
 285.0,
 49.0,
 88.9,
 32.0,
 305.0,
 102.6,
 5165.0,
 68.9,
 62.0,
 235.0,
 125.0,
 83.0,
 81.1,
 105.0,
 165.0,
 315.0,
 23.0,
 100.0,
 205.0,
 63.0,
 105.0,
 135.0,
 51.9,
 205.0,
 73.0,
 50.0,
 145.0,
 185.0,
 645.0,
 34.8,
 365.0,
 135.0,
 48.2,
 62.0,
 115.0,
 104.0,
 52.1,
 53.9,
 135.0,
 135.0,
 135.0,
 125.0,
 115.0,
 105.0,
 52.2,
 325.0,
 455.0,
 165.0,
 34.0,
 82.9,
 74.5,
 53.0,
 185.0,
 60.4,
 100.0,
 125.0,
 55.0,
 59.7,
 135.0,
 115.0,
 74.5,
 79.0,
 6705.0,
 73.0,
 60.9,
 68.1,
 155.0,
 34.3,
 79.0,
 65.0,
 49.7,
 30.4,
 67.9,
 165.0,
 80.6,
 52.1,
 125.0,
 51.0,
 37.5,
 47.9,
 71.0,
 33.0,
 135.0,
 61.6,
 85.3,
 115.0,
 59.0,
 81.1,
 26.4,
 62.0,
 215.0,
 77.9,
 46.9,
 103.0,
 105.0,
 165.0,
 40.0,
 35.0,
 535.0,
 225.0,
 92.0,
 5075.0,
 155.0,
 92.0,
 155.0,
 77.0,
 35.0,
 245.0,
 135.0,
 38.0,
 125.0,
 155.0,
 81.0,
 90.0,
 325.0,
 105.0,
 93.9,
 115.0,
 58.0,
 28.1,
 145.0,
 95.0,
 37.8,
 48.0,
 105.0,
 36.1,
 185.0,
 63.7,
 325.0,
 63.0,
 61.0,
 58.0,
 94.0,
 115.0,
 51.8,
 24.3,
 93.0,
 16.9,
 71.1,
 345.0,
 65.0,
 62.0,
 145.0,
 145.0,
 41.1,
 46.0,
 195.0,
 56.0,
 20.9,
 86.3,
 88.0,
 115.0,
 175.0,
 86.9,
 115.0,
 465.0,
 285.0,
 105.0,
 38.0,
 90.0,
 54.0,
 135.0,
 115.0,
 43.0,
 115.0,
 145.0,
 265.0,
 115.0,
 50.0,
 105.0,
 31.5,
 125.0,
 155.0,
 165.0,
 62.0,
 175.0,
 95.0,
 31.3,
 70.0,
 115.0,
 52.0,
 125.0,
 82.2,
 66.4,
 90.0,
 59.0,
 37.0,
 165.0,
 185.0,
 125.0,
 79.8,
 43.2,
 155.0,
 54.0,
 96.9,
 73.0,
 135.0,
 63.0,
 57.0,
 155.0,
 77.2,
 70.0,
 64.0,
 58.4,
 135.0,
 72.6,
 105.0,
 46.0,
 275.0,
 90.0,
 135.0,
 37.9,
 75.0,
 81.8,
 16.9,
 295.0,
 105.0,
 51.0,
 65.0,
 66.0,
 215.0,
 84.9,
 34.4,
 375.0,
 115.0,
 115.0,
 68.2,
 355.0,
 165.0,
 285.0,
 335.0,
 135.0,
 50.0,
 89.7,
 88.0,
 125.0,
 9325.0,
 45.0,
 63.0,
 51.7,
 125.0,
 70.0,
 64.2,
 245.0,
 65.3,
 30.0,
 49.3,
 56.0,
 165.0,
 70.0,
 41.5,
 61.0,
 60.4,
 68.0,
 47.1,
 59.0,
 54.5,
 255.0,
 195.0,
 81.0,
 40.0,
 94.9,
 125.0,
 85.0,
 58.4,
 60.0,
 515.0,
 155.0,
 56.9,
 28.4,
 135.0,
 31.0,
 49.3,
 115.0,
 43.0,
 63.5,
 145.0,
 60.0,
 54.0,
 29.1,
 185.0,
 57.6,
 81.0,
 32.0,
 165.0,
 175.0,
 165.0,
 93.0,
 75.0,
 65.0,
 74.0,
 27.9,
 70.0,
 54.7,
 145.0,
 87.0,
 155.0,
 155.0,
 90.0,
 84.0,
 28.2,
 165.0,
 125.0,
 78.0,
 101.5,
 80.0,
 92.0,
 175.0,
 245.0,
 175.0,
 60.1,
 36.5,
 125.0,
 51.0,
 115.0,
 155.0,
 65.3,
 85.0,
 84.0,
 80.0,
 37.1,
 39.0,
 28.0,
 52.0,
 58.0,
 57.8,
 34.9,
 76.2,
 265.0,
 135.0,
 295.0,
 79.5,
 95.0,
 43.0,
 86.0,
 47.0,
 145.0,
 96.0,
 100.0,
 69.7,
 57.0,
 215.0,
 95.0,
 31.2,
 76.2,
 100.0,
 105.0,
 80.0,
 60.0,
 205.0,
 335.0,
 135.0,
 165.0,
 95.0,
 34.0,
 33.0,
 67.0,
 115.0,
 50.0,
 255.0,
 51.4,
 86.0,
 98.0,
 34.9,
 23.5,
 275.0,
 72.5,
 85.0,
 195.0,
 88.5,
 545.0,
 135.0,
 32.5,
 71.0,
 85.7,
 135.0,
 80.5,
 43.0,
 49.8,
 84.0,
 105.0,
 32.2,
 33.5,
 24.6,
 355.0,
 37.7,
 245.0,
 85.0,
 195.0,
 38.0,
 90.7,
 175.0,
 45.0,
 36.0,
 73.0,
 60.0,
 165.0,
 62.0,
 72.0,
 84.2,
 85.0,
 315.0,
 36.9,
 58.7,
 100.0,
 105.0,
 30.0,
 135.0,
 125.0,
 33.0,
 70.0,
 39.5,
 88.0,
 145.0,
 195.0,
 195.0,
 79.0,
 43.1,
 195.0,
 6465.0,
 85.0,
 92.4,
 54.6,
 36.0,
 91.4,
 305.0,
 145.0,
 78.0,
 245.0,
 39.5,
 57.0,
 97.0,
 100.5,
 41.5,
 91.0,
 50.0,
 61.4,
 92.0,
 55.0,
 76.5,
 39.0,
 69.0,
 175.0,
 7835.0,
 50.6,
 95.0,
 80.0,
 905.0,
 59.0,
 175.0,
 32.0,
 155.0,
 96.3,
 285.0,
 32.0,
 53.0,
 60.3,
 65.0,
 69.1,
 20.9,
 65.0,
 93.0,
 105.0,
 50.9,
 205.0,
 145.0,
 30.8,
 105.0,
 48.0,
 405.0,
 47.0,
 88.7,
 83.0,
 85.0,
 70.0,
 52.0,
 115.0,
 30.0,
 325.0,
 255.0,
 125.0,
 1055.0,
 89.9,
 125.0,
 275.0,
 245.0,
 46.0,
 195.0,
 435.0,
 255.0,
 33.0,
 185.0,
 67.0,
 41.0,
 70.0,
 25.0,
 205.0,
 30.0,
 195.0,
 185.0,
 71.0,
 58.0,
 58.2,
 80.0,
 155.0,
 27.0,
 85.0,
 215.0,
 64.8,
 145.0,
 255.0,
 43.0,
 61.5,
 55.0,
 37.5,
 53.0,
 145.0,
 38.5,
 34.1,
 185.0,
 27.6,
 66.5,
 52.0,
 62.0,
 255.0,
 535.0,
 35.0,
 68.3,
 235.0,
 70.0,
 315.0,
 88.0,
 40.0,
 85.0,
 69.0,
 83.5,
 105.0,
 39.9,
 225.0,
 84.8,
 48.0,
 48.0,
 54.5,
 115.0,
 37.2,
 100.0,
 125.0,
 1115.0,
 101.0,
 155.0,
 115.0,
 205.0,
 135.0,
 155.0,
 75.0,
 175.0,
 97.0,
 285.0,
 125.0,
 195.0,
 62.0,
 44.0,
 135.0,
 57.5,
 125.0,
 29.8,
 33.2,
 85.2,
 30.2,
 61.0,
 30.0,
 40.0,
 44.1,
 20.9,
 100.0,
 63.0,
 275.0,
 80.0,
 215.0,
 49.0,
 51.5,
 175.0,
 43.5,
 185.0,
 51.1,
 66.0,
 61.0,
 69.0,
 69.9,
 145.0,
 40.5,
 355.0,
 44.8,
 62.0,
 75.0,
 89.1,
 455.0,
 185.0,
 97.0,
 61.0,
 80.0,
 115.0,
 85.0,
 77.5,
 52.0,
 105.0,
 34.9,
 145.0,
 105.0,
 135.0,
 93.1,
 78.0,
 71.0,
 60.0,
 98.0,
 135.0,
 215.0,
 103.0,
 41.0,
 74.0,
 30.0,
 61.5,
 72.0,
 105.0,
 165.0,
 65.0,
 68.8,
 52.7,
 155.0,
 50.0,
 75.6,
 30.5,
 245.0,
 36.5,
 285.0,
 21.7,
 38.7,
 73.0,
 83.0,
 29.9,
 84.5,
 135.0,
 43.0,
 175.0,
 145.0,
 29.0,
 185.0,
 575.0,
 31.0,
 67.7,
 285.0,
 53.1,
 99.7,
 9605.0,
 71.8,
 101.0,
 175.0,
 295.0,
 215.0,
 165.0,
 285.0,
 38.0,
 135.0,
 90.0,
 135.0,
 59.3,
 88.0,
 56.2,
 65.0,
 485.0,
 64.5,
 75.2,
 37.5,
 36.4,
 50.5,
 31.1,
 75.0,
 84.9,
 72.9,
 63.4,
 135.0,
 9545.0,
 83.0,
 25.0,
 295.0,
 445.0,
 42.0,
 295.0,
 89.7,
 105.0,
 74.5,
 67.0,
 73.0,
 56.0,
 50.0,
 45.0,
 72.1,
 305.0,
 25.6,
 71.9,
 115.0,
 83.0,
 215.0,
 115.0,
 65.0,
 175.0,
 195.0,
 245.0,
 83.0,
 103.0,
 545.0,
 100.0,
 41.0,
 64.0,
 75.0,
 525.0,
 185.0,
 51.3,
 49.5,
 ...]

In [27]:
d1["New_Target"]=With_Increment

C:\Users\Aadesh\AppData\Local\Temp\ipykernel_11464\3705555557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d1["New_Target"]=With_Increment

In [28]:
d1

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS),New_Target
7,Owner,0.0,1,3,BHK,1181.012946,1,1,"Kharar,Mohali",30.740000,76.650000,52.0,57.0
13,Owner,0.0,1,2,BHK,1122.171946,1,1,"Sector-119 Noida,Noida",28.587711,77.403123,62.0,67.0
15,Dealer,1.0,1,3,BHK,1394.117647,0,1,"Sector-150 Noida,Noida",28.429614,77.481711,71.1,76.1
17,Dealer,1.0,1,3,BHK,2124.896706,0,1,"Konanakunte,Bangalore",12.885500,77.563800,180.0,185.0
19,Dealer,0.0,1,3,BHK,2178.649237,1,1,"Kogilu,Bangalore",13.092356,77.613468,120.0,125.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29430,Owner,0.0,1,3,BHK,1265.060241,1,1,"Chromepet,Chennai",12.951610,80.140970,63.0,68.0
29436,Owner,1.0,1,2,BHK,1175.132676,0,1,"Whitefield,Bangalore",12.995893,77.761394,62.0,67.0
29439,Dealer,1.0,1,2,BHK,975.609756,0,1,"Laxmi Nagar,Lalitpur",22.281215,70.789479,120.0,125.0
29443,Dealer,0.0,1,3,BHK,1161.194975,1,1,"Marol,Maharashtra",19.111438,72.878724,220.0,225.0
29450,Dealer,0.0,1,2,BHK,896.774194,1,1,"Jagatpura,Jaipur",26.832353,75.841749,27.8,32.8